# Add helm.sh/resource-policy annotation to prevent CRD deletion during upgrades
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: platformnetworks.starlingx.windriver.com
  annotations:
    helm.sh/resource-policy: keep
